AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  VeevaPoC
  Sample SAM Template for VeevaPoC
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Parameters:
  CloudWatchLogLevel:
      Type: String
      Default: ERROR
      AllowedValues:
        - ALL
        - ERROR
        - FATAL
        - OFF
  StepFunctionName:
    Description: The state function name.
    Type: String
    Default: VeevaPoC2
    
  VeevaDestinationS3Bucket:
    Description: The S3 bucket used by AppFlow to save data from Veeva
    Type: String
    Default: "veeva-poc-bucket2"

  VeevaAppFlowName:
    Description: The name of the AppFlow Flow to ingest data from veeva
    Type: String
    Default: "VeevaPoC2" 

  AppFlowVeevaConnectorName:
    Description: The name of the veeva connector
    Type: String
    Default: "veeva" 

Resources:
  AppFlowVeevaLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/veeva/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Tracing: Active
      Environment:
        Variables:
          GlueCatalogTable: salesforce_patient_s3   
          GlueCatalogDatabase: appflow-datalake-demo
          GlueTableKey: patientid__c      
      MemorySize: 2048
      Policies: # For PRODUCTION you may want to recify the permission boundries. At the moment the lambda function will have access to all S3 buckets and SQS queues. 
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Timeout: 300
      
  AppFlowHealthlakeResource:
      Type: AWS::Serverless::Function
      Properties:
        Handler: src/healthlake/com.amazonaws.samples.AppFlowDataHandler::handleRequest
        Runtime: java11
        MemorySize: 512
        Timeout: 300
        Tracing: Active
        Environment:
          Variables:
            SERVICE_NAME: AppFlowDataHandler
            HL_ENDPOINT: https://healthlake.us-east-1.amazonaws.com/datastore/e381924cd2549ed29646ba42a1d376f3/r4/

        Policies:
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource:
                - 'arn:aws:s3:::*'
            - Effect: Allow
              Action:
                - "healthlake:*"
              Resource:
                - '*'

  # Definition of our AWS Step Function. The actual ASL is extracted in statemachine/RealWorldExample.asl.json file.          
  StateMachine:
    Type: AWS::Serverless::StateMachine
    DependsOn: ProcessingStateMachineLogGroup
    Properties:
      Name: !Sub ${StepFunctionName}
      DefinitionUri: src/statemachine/VeevaPoC.asl.json
      DefinitionSubstitutions:
        LambdaFunctionArn: !GetAtt AppFlowVeevaLambdaFunction.Arn
      Type: "STANDARD"  
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt ProcessingStateMachineLogGroup.Arn
              
        IncludeExecutionData: false
        Level: !Ref CloudWatchLogLevel 
      Role: !GetAtt StatesExecutionRole.Arn            
      
  # Execution Role to allow Step Function to InvokeLambda, Log data into CloudWatch, publish events in EvnetBridge          
  StatesExecutionRole:
    DependsOn: ProcessingStateMachineLogGroup
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
                - !Sub states.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"   
      Policies:
        - PolicyName: StatesLoggingPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: "*"
                
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Join [ ":*", [!GetAtt AppFlowVeevaLambdaFunction.Arn, ""]]
                
  # Define CloudWatch Log Group for State execution logs
  ProcessingStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "stepfunctions/${StepFunctionName}"                
      
  LoggingBucket:
    Type: "AWS::S3::Bucket"
    
  LoggingBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: "2012-10-17"    
        Statement:
        - Effect: Allow
          Principal:
            Service: "cloudtrail.amazonaws.com"
          Action: "s3:GetBucketAcl"
          Resource: !Sub "arn:aws:s3:::${LoggingBucket}"
        - Effect: Allow
          Principal:
            Service: "cloudtrail.amazonaws.com"
          Action: "s3:PutObject"
          Resource: !Sub "arn:aws:s3:::${LoggingBucket}/AWSLogs/${AWS::AccountId}/*"
          Condition:
            StringEquals:
              "s3:x-amz-acl": "bucket-owner-full-control"

  SourceBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref VeevaDestinationS3Bucket

  SourceBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: !Ref SourceBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service: appflow.amazonaws.com
          Action:
          - s3:PutObject
          - s3:AbortMultipartUpload
          - s3:ListMultipartUploadParts
          - s3:ListBucketMultipartUploads
          - s3:GetBucketAcl
          - s3:PutObjectAcl
          Resource:
          - !Sub arn:aws:s3:::${VeevaDestinationS3Bucket}
          - !Sub arn:aws:s3:::${VeevaDestinationS3Bucket}/*      
    
  CloudTrail:
    Type: "AWS::CloudTrail::Trail"
    DependsOn:
      - LoggingBucketPolicy
    Properties:
      IsLogging: true
      S3BucketName: !Ref LoggingBucket 
      EventSelectors:
        - DataResources:
            - Type: "AWS::S3::Object"
              Values:
                - "arn:aws:s3:::"  # log data events for all S3 buckets
                - !Sub "${SourceBucket.Arn}/${VeevaAppFlowName}" # log data events for the S3 bucket defined above
          IncludeManagementEvents: true
          ReadWriteType: WriteOnly

  EventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "EventRule"
      State: "ENABLED"
      EventPattern: 
        source: 
          - "aws.s3"
        detail: 
          eventName: 
            - "PutObject"
          requestParameters:
            bucketName: 
              - !Ref SourceBucket

      Targets: 
        - 
          Id: !Ref StepFunctionName
          Arn: !GetAtt StateMachine.Arn
          RoleArn: !GetAtt EventsExecutionRole.Arn

  EventsExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - events.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"   
      Policies:
        - PolicyName: Amazon_EventBridge_Invoke_Step_Functions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 
                  - states:StartExecution
                Resource: !GetAtt StateMachine.Arn
  KSMKey: 
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key to be used by AppFlow.
      EnableKeyRotation: true
      PendingWindowInDays: 20
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Sub "${VeevaAppFlowName}-KMS"
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
          Action: kms:*
          Resource: "*"        
        - Sid: Allow access through Amazon AppFlow for all principals in the account that
            are authorized to use Amazon AppFlow
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey*
          - kms:CreateGrant
          - kms:DescribeKey
          Resource: "*"
          Condition:
            StringEquals:
              kms:CallerAccount: !Sub "${AWS::AccountId}"
              kms:ViaService: !Sub "appflow.${AWS::Region}.amazonaws.com"

        - Sid: Allow access through S3 for all principals in the account that are authorized
            to use S3
          Effect: Allow
          Principal:
            AWS: "*"
          Action: kms:Decrypt
          Resource: "*"
          Condition:
            StringEquals:
              kms:CallerAccount: !Sub "${AWS::AccountId}"
              kms:ViaService: !Sub "s3.${AWS::Region}.amazonaws.com"
        - Sid: Allow access through SecretManager for all principals in the account that are
            authorized to use SecretManager
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey*
          - kms:CreateGrant
          - kms:DescribeKey
          Resource: "*"
          Condition:
            StringEquals:
              kms:CallerAccount: !Sub "${AWS::AccountId}"
              kms:ViaService: !Sub "secretsmanager.${AWS::Region}.amazonaws.com"
           
  AppFlowVeeva:
    DependsOn: SourceBucket
    Type: AWS::AppFlow::Flow
    Properties: 
      Description: String
      DestinationFlowConfigList:
      - ConnectorType: S3
        DestinationConnectorProperties:
          S3:
            BucketName: !Ref VeevaDestinationS3Bucket
            S3OutputFormatConfig:
              FileType: JSON
      FlowName: !Ref VeevaAppFlowName
      KMSArn: !GetAtt KSMKey.Arn
      SourceFlowConfig: 
          ConnectorProfileName: !Ref AppFlowVeevaConnectorName
          ConnectorType: "Veeva" 
          SourceConnectorProperties:
              Veeva: 
                DocumentType: "Reference"
                Object: "documents/types/reference__c"
      Tasks:
      - ConnectorOperator:
          Veeva: PROJECTION
        SourceFields:
        - id
        - reference_source__c
        TaskType: Filter
      - ConnectorOperator:
          Veeva: NO_OP
        DestinationField: id
        SourceFields:
        - id
        TaskProperties:
        - Key: DESTINATION_DATA_TYPE
          Value: id
        - Key: SOURCE_DATA_TYPE
          Value: id
        TaskType: Map
      - ConnectorOperator:
          Veeva: NO_OP
        DestinationField: reference_source__c
        SourceFields:
        - reference_source__c
        TaskProperties:
          - Key: DESTINATION_DATA_TYPE 
            Value: String
          - Key: SOURCE_DATA_TYPE
            Value:  String
        TaskType: Map
      TriggerConfig:
        TriggerType: OnDemand